version: '3.8'

services:
  expertdb:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/db/sqlite/main.db
      - UPLOAD_PATH=/app/data/documents
      - LOG_DIR=/app/logs
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
      - ADMIN_EMAIL=admin@expertdb.com
      - ADMIN_NAME=Admin User
      - ADMIN_PASSWORD=adminpassword
    volumes:
      # Persist database, uploads, and logs
      - expertdb_data:/app/data
      - expertdb_logs:/app/logs
      - expertdb_db:/app/db/sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  expertdb_data:
    driver: local
  expertdb_logs:
    driver: local
  expertdb_db:
    driver: local
