version: '3.8'

services:
  expertdb-backend:
    build: .
    container_name: expertdb-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - DB_PATH=/app/data/expertdb.sqlite
      - UPLOAD_PATH=/app/data/documents
      - CORS_ALLOWED_ORIGINS=*
      - AI_SERVICE_URL=http://expertdb-ai:9000
    restart: unless-stopped
    networks:
      - expertdb-network

networks:
  expertdb-network:
    driver: bridge